### ISSUE TITLE
fs/promises

### ISSUE THREAD

**Issue by robynjayqueerie** [RandomStudio/omxconductor#11]
## Bug report

Running omxplayer under Node 12.22.1 and getting error Cannot find module 'fs/promises'

### Current behaviour

Tried writing my own code to use omxplayer, got the above error. Searched and found indication that Node v12 had the fs/promises so I upgraded to Node 12.22.1, still had issue.
Ran the demo program as supplied on GitHub, same issue, the full error log from the terminal is as follows

pi@raspberrypi:~/ptzcontrol $ node demo.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /home/pi/ptzcontrol/node_modules/omxconductor/dist/player.js
- /home/pi/ptzcontrol/node_modules/omxconductor/dist/index.js
- /home/pi/ptzcontrol/demo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/ptzcontrol/node_modules/omxconductor/dist/player.js:17:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/ptzcontrol/node_modules/omxconductor/dist/player.js',
    '/home/pi/ptzcontrol/node_modules/omxconductor/dist/index.js',
    '/home/pi/ptzcontrol/demo.js'
  ]
}
pi@raspberrypi:~/ptzcontrol $

```ts
Code is unmodified from the demo on GitHub
```

[issue demo](https://codesandbox.io/)

### Expected behaviour
In searching for a solution I did find that the fs/promises is associated with Typescript, wondering if the last action you fixed which was also associated with Typescript is involved here? I don't have Typescript installed on the Pi i am using, basically latest OS and full upgrade, only thing added at this stage is Node and Express.
Should I be installing some other module or is this a bug that we have here?
Thanks for your help, omxplayer looks like the bees knees for what I am attempting to do but I want to learn how to run it properly

_Please explain how you'd expect it to behave._

**Comment by robynjayqueerie** [comment]
BTW - I have just installed Typescript on the Pi and it did not change the result, still the same error.
Robyn

**Comment by robynjayqueerie** [comment]
The following link is relevant ? https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly 
I suspect that the line import fs from "fs/promises"; in player.ts should be import fs from "(fs)".promises; or some version of that to suit the latest Node. From what I read Node should accept both formats but I am guessing it doesn't.
Sorry if this is a red herring!

**Comment by anselanza** [comment]
Curious. This might just be something affecting the demo, rather than the library itself? I should actually check that the demo is still up to date and working!

**Comment by anselanza** [comment]
Hmmm, nope the demo appears to be working.

And in any case I guess your "demo.js" file is a different program altogether.

Looking at the Stackoverflow post you included, I would say that Node 12 is probably not supported properly.

Installing Node 14 (or later) should do the trick.

**Comment by robynjayqueerie** [comment]
Thanks, the demo.js I was running was your one, just copied from the zip download.
I have installed Node 14 and the demo now runs, thank you, I will push on with my development and see where I get to
Robyn
