### ISSUE TITLE
Ability to play udp stream

### ISSUE THREAD

**Issue by ServiceTo** [RandomStudio/omxconductor#5]
### Use case(s)

I'm trying to play a UDP stream and have it restart automatically when omxplayer detects it's not playing.  So far a difficult task.  I found your project and it looks promising but I'm blocked at the get-go by it looking in the filesystem for my UDP stream.  udp://239.255.42.42:5004

```
error on open: { filePath: '/home/pi/thing/udp:/239.255.42.42:5004',
  err:
   { Error: ENOENT: no such file or directory, stat '/home/pi/thing/udp:/239.255.42.42:5004'
     errno: -2,
     code: 'ENOENT',
     syscall: 'stat',
     path: '/home/pi/thing/udp:/239.255.42.42:5004' } }
```

My demo script...
```ts
const { Player } = require('omxconductor')
const player = new Player('udp://239.255.42.42:5004', { loop: true })
player
  .open()
  .then((result) => {
    console.log('Clip started playing OK! Some information:', result)
  })
  .catch((err) => {
    console.error('error on open:', err)
  })
```

Ideally, I'd like it to play the udp stream and "loop" (ie: re-connect to the broadcast) when it's no longer playing

Ability to stream to multiple raspberry pi using one multi-cast stream and move devices into different untagged VLANs for different streams.

**Comment by anselanza** [comment]
Ah, I have never used omxplayer for UDP streams, and so I literally never thought to check for anything other than files.

I will need to look into this a bit more. Seems completely sensible, since omxplayer does in fact support this natively!

**Comment by anselanza** [comment]
@ServiceTo Hopefully https://github.com/RandomStudio/omxconductor/pull/13 will address at least the basics. Re-opening streams that fail/close could be achieved easily by listening for the "close" or "error" events, e.g. 
```
player.on("close", (result) => {
 player = new Player(.... // basically, make a new instance
}
```

**Comment by ServiceTo** [comment]
@anselanza Amazing! I'll set up my lab environment again and give it a try some time this week!

**Comment by anselanza** [comment]
Going to merge this into a new version (v2.3.0)
