### ISSUE TITLE
TypeScript required?

### ISSUE THREAD

**Issue by namxam** [RandomStudio/omxconductor#6]
Is typescript required, because adding it via NPM causes a crash

```
Error: Cannot find module 'tslib'
Require stack:
- /home/pi/media-player/node_modules/omxconductor/bundles/index.umd.js
```

**Comment by anselanza** [comment]
Typescript should not be required in your project in order to import and use the library, no.

**Comment by anselanza** [comment]
Ah, thank you for finding this error. Typescript should NOT be required, but I am also seeing the error you are, when using in a non-typescript project! Will investigate.
